export type EnvTypeEntry = {
  key: string;
  comment?: string;
};

export type GenerateEnvTypesOptions = {
  /** Also augment `NodeJS.ProcessEnv` with the secret keys. */
  processEnv?: boolean;
};

const VALID_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const renderProperty = (entry: EnvTypeEntry, indent: string) => {
  const name = VALID_IDENTIFIER.test(entry.key) ? entry.key : JSON.stringify(entry.key);
  const comment = entry.comment?.trim().replace(/\*\//g, "*\\/").replace(/\s*\r?\n\s*/g, " ");

  return `${comment ? `${indent}/** ${comment} */\n` : ""}${indent}${name}: string;`;
};

/**
 * Renders a TypeScript declaration file that registers the given secret keys on the `InfisicalSecrets` interface.
 */
export const generateEnvTypes = (entries: EnvTypeEntry[], options: GenerateEnvTypesOptions = {}) => {
  const unique = new Map<string, EnvTypeEntry>();
  for (const entry of entries) {
    if (!unique.has(entry.key)) {
      unique.set(entry.key, entry);
    }
  }
  const sorted = Array.from(unique.values()).sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));

  const lines = [
    "// This file is auto-generated by @infisical/sdk. Do not edit it manually.",
    "",
    'declare module "@infisical/sdk" {',
    "  interface InfisicalSecrets {",
    ...sorted.map((entry) => renderProperty(entry, "    ")),
    "  }",
    "}",
  ];

  if (options.processEnv) {
    lines.push(
      "",
      "declare global {",
      "  namespace NodeJS {",
      "    interface ProcessEnv {",
      ...sorted.map((entry) => renderProperty(entry, "      ")),
      "    }",
      "  }",
      "}"
    );
  }

  lines.push("", "export {};", "");

  return lines.join("\n");
};
