import { describe, it, expect, vi, afterEach, expectTypeOf } from "vitest";
import { mkdtemp, readFile } from "fs/promises";
import { tmpdir } from "os";
import { join } from "path";
import { z } from "zod";
import SecretsClient from "../src/custom/secrets";
import { generateEnvTypes } from "../src/custom/typegen";
import type { SecretsApi } from "../src/api/endpoints/secrets";

const secret = (secretKey: string, secretValue: string, secretComment?: string) =>
	({ secretKey, secretValue, secretComment }) as any;

const clientWith = (response: { secrets: any[]; imports?: any[] }) => {
	const listSecrets = vi.fn().mockImplementation(async () => structuredClone(response));
	return { client: new SecretsClient({ listSecrets } as unknown as SecretsApi), listSecrets };
};

const options = { projectId: "project", environment: "dev" };

describe("secrets().getEnv", () => {
	afterEach(() => {
		delete process.env.TYPED_ENV_TEST;
	});

	it("returns secrets as a key/value object, with own secrets taking priority over imports", async () => {
		const { client, listSecrets } = clientWith({
			secrets: [secret("PORT", "8080")],
			imports: [{ secretPath: "/shared", environment: "dev", secrets: [secret("PORT", "1"), secret("API_KEY", "abc")] }],
		});

		const env = await client.getEnv(options);

		expect(env).toEqual({ PORT: "8080", API_KEY: "abc" });
		expect(listSecrets.mock.calls[0][0].include_imports).toBe("true");
	});

	it("skips imports when includeImports is false", async () => {
		const { client, listSecrets } = clientWith({ secrets: [secret("PORT", "8080")] });

		await client.getEnv({ ...options, includeImports: false });

		expect(listSecrets.mock.calls[0][0].include_imports).toBe("false");
	});

	it("validates and types the result with a schema", async () => {
		const { client } = clientWith({ secrets: [secret("PORT", "8080"), secret("DEBUG", "true"), secret("EXTRA", "x")] });

		const env = await client.getEnv({
			...options,
			schema: z.object({ PORT: z.coerce.number(), DEBUG: z.enum(["true", "false"]).transform((v) => v === "true") }),
		});

		expectTypeOf(env).toEqualTypeOf<{ PORT: number; DEBUG: boolean }>();
		expect(env).toEqual({ PORT: 8080, DEBUG: true });
	});

	it("throws the schema error when secrets are missing", async () => {
		const { client } = clientWith({ secrets: [] });

		await expect(client.getEnv({ ...options, schema: z.object({ PORT: z.string() }) })).rejects.toThrow(z.ZodError);
	});

	it("accepts an explicit generic and attaches to process.env", async () => {
		const { client } = clientWith({ secrets: [secret("TYPED_ENV_TEST", "yes")] });

		const env = await client.getEnv<{ TYPED_ENV_TEST: string }>({ ...options, attachToProcessEnv: true });

		expectTypeOf(env).toEqualTypeOf<{ TYPED_ENV_TEST: string }>();
		expect(process.env.TYPED_ENV_TEST).toBe("yes");
	});
});

describe("generateEnvTypes", () => {
	it("renders a sorted, de-duplicated module augmentation", () => {
		const types = generateEnvTypes([
			{ key: "PORT" },
			{ key: "API_KEY", comment: "Stripe key\nends */ here" },
			{ key: "my-key" },
			{ key: "PORT" },
		]);

		expect(types).toBe(`// This file is auto-generated by @infisical/sdk. Do not edit it manually.

declare module "@infisical/sdk" {
  interface InfisicalSecrets {
    /** Stripe key ends *\\/ here */
    API_KEY: string;
    PORT: string;
    "my-key": string;
  }
}

export {};
`);
	});

	it("augments NodeJS.ProcessEnv when requested", () => {
		const types = generateEnvTypes([{ key: "PORT" }], { processEnv: true });

		expect(types).toContain("namespace NodeJS");
		expect(types).toContain("      PORT: string;");
	});
});

describe("secrets().generateTypes", () => {
	it("never requests secret values and writes the output file", async () => {
		const { client, listSecrets } = clientWith({ secrets: [secret("PORT", "<hidden>", "HTTP port")] });
		const outputFile = join(await mkdtemp(join(tmpdir(), "infisical-typegen-")), "env.d.ts");

		const types = await client.generateTypes({ ...options, outputFile });

		expect(listSecrets.mock.calls[0][0].viewSecretValue).toBe("false");
		expect(types).toContain("/** HTTP port */\n    PORT: string;");
		expect(await readFile(outputFile, "utf8")).toBe(types);
	});
});
